<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AlmacenWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AlmacenWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AlmacenWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsAlmacen/">
    <import location="http://localhost:32093/TiendaElectronicaV2/Almacen?WSDL" namespace="http://wsAlmacen/"/>
    <plnk:partnerLinkType name="AlmacenLinkType">
        <plnk:role name="AlmacenRole" portType="ns:Almacen"/>
    </plnk:partnerLinkType>
</definitions>
