<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="EnvioPaquetesWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/EnvioPaquetesWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/EnvioPaquetesWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsMensajeria/">
    <import location="http://localhost:32093/MensajeriaExpressV2/EnvioPaquetes?WSDL" namespace="http://wsMensajeria/"/>
    <plnk:partnerLinkType name="EnvioPaquetesLinkType">
        <plnk:role name="EnvioPaquetesRole" portType="ns:EnvioPaquetes"/>
    </plnk:partnerLinkType>
</definitions>
